# sample netlify.toml
[build]
  functions = "./functions" # netlify dev uses this to know where to scaffold and serve your functions
  # publish = "public"

  # explicit commands for building the site
  # and the folder to publish

  command = "npm run build"
  publish = "build"

[build.environment]
  # cache Cypress binary in local "node_modules" folder
  # so Netlify caches it
  CYPRESS_CACHE_FOLDER = "./node_modules/CypressBinary"
  # set TERM variable for terminal output
  TERM = "xterm"

