# sample netlify.toml
[build]
  functions = "./functions" # netlify dev uses this to know where to scaffold and serve your functions
  # publish = "public"

  # explicit commands for building the site
  # and the folder to publish
  command = "npm run build"
  publish = "build"
